# Generated by Django 5.0.6 on 2024-06-16 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Assistants",
            new_name="Ticket",
        ),
    ]
