# Generated by Django 5.0.6 on 2024-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=240)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("artists", models.ManyToManyField(to="events.artist")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=240)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("end_date", models.DateField()),
                ("artists", models.ManyToManyField(to="events.artist")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
