# Generated by Django 5.0.6 on 2024-06-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="artists",
            field=models.ManyToManyField(related_name="concert", to="events.artist"),
        ),
        migrations.AlterField(
            model_name="festival",
            name="artists",
            field=models.ManyToManyField(related_name="festival", to="events.artist"),
        ),
    ]
